# Generated by Django 3.1.1 on 2020-09-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoNContact', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
