# Generated by Django 2.2.5 on 2020-09-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0008_comment'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complain.Complain')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tag.Tag')),
            ],
        ),
    ]
