# Generated by Django 3.0.3 on 2020-09-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0013_auto_20200930_1710'),
        ('Tag', '0003_auto_20200928_0016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaintag',
            unique_together={('complain', 'tag')},
        ),
    ]
