# Generated by Django 3.0.3 on 2020-10-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0006_ajairamodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ajairamodel',
        ),
        migrations.DeleteModel(
            name='ajairamodel2',
        ),
    ]
