# Generated by Django 3.0.3 on 2020-10-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0007_auto_20201005_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplainTag',
        ),
    ]
