# Generated by Django 3.0.3 on 2020-10-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0009_tag2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag2',
        ),
    ]
