# Generated by Django 3.0.3 on 2020-09-22 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0005_auto_20200922_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('1', 'Approved'), ('2', 'Not Approved'), ('3', 'Pending')], default='1', max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('1', 'General'), ('2', 'Departmental'), ('3', 'Both')], default='1', max_length=100)),
                ('date', models.DateField(verbose_name=datetime.date)),
                ('time', models.TimeField(verbose_name=datetime.time)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
    ]
