# Generated by Django 3.0.3 on 2020-10-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Verified_User', '0003_auto_20200929_1529'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Verified_User.Verified_User')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complain/image/')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Not Approved', 'Pending')], default='Approved', max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('General', 'General'), ('Departmental', 'Departmental'), ('Both', 'Both')], default='General', max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('comment', models.ManyToManyField(blank=True, to='Complain.Comment')),
                ('tag', models.ManyToManyField(blank=True, to='Tag.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Verified_User.Verified_User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
