# Generated by Django 3.0.3 on 2020-09-22 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
