# Generated by Django 3.0.3 on 2020-09-22 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0002_auto_20200922_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateField(default=datetime.date, verbose_name=datetime.date),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.TimeField(default=datetime.time, verbose_name=datetime.time),
        ),
    ]
