# Generated by Django 3.0.3 on 2020-09-22 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0004_auto_20200922_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.CharField(default=datetime.date, max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.CharField(default=datetime.time, max_length=50),
        ),
    ]
