# Generated by Django 3.0.3 on 2020-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0005_auto_20200922_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
