# Generated by Django 3.0.3 on 2020-09-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20200922_0106'),
        ('Complain', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False, null=True)),
                ('downvote', models.BooleanField(default=False, null=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complain.Complain')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
            options={
                'unique_together': {('complain', 'student')},
            },
        ),
    ]
