# Generated by Django 3.0.3 on 2020-09-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0009_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=models.ImageField(blank=True, upload_to='complain/image/'),
        ),
    ]
