# Generated by Django 3.0.3 on 2020-09-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Verified_User', '0001_initial'),
        ('Complain', '0010_auto_20200923_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='student',
        ),
        migrations.AddField(
            model_name='comment',
            name='verified_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Verified_User.Verified_User'),
        ),
        migrations.AddField(
            model_name='complain',
            name='verified_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Verified_User.Verified_User'),
        ),
        migrations.AddField(
            model_name='vote',
            name='verified_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Verified_User.Verified_User'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('complain', 'verified_user')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='student',
        ),
    ]
