# Generated by Django 3.0.3 on 2020-09-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Verified_User', '0003_auto_20200929_1529'),
        ('Complain', '0011_auto_20200928_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='verified_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='verified_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='verified_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('complain', 'user')},
        ),
    ]
