# Generated by Django 3.0.3 on 2020-09-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0012_auto_20200929_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complain/image/'),
        ),
    ]
