# Generated by Django 3.0.3 on 2020-10-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0008_delete_complaintag'),
        ('Complain', '0013_auto_20200930_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='complain',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='complain',
            name='comment',
            field=models.ManyToManyField(to='Complain.Comment'),
        ),
        migrations.AddField(
            model_name='complain',
            name='tag',
            field=models.ManyToManyField(to='Tag.Tag'),
        ),
        migrations.AddField(
            model_name='complain',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Complain.Vote'),
        ),
        migrations.AddField(
            model_name='vote',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='complain',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
    ]
