# Generated by Django 3.0.3 on 2020-10-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0014_auto_20201005_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='comment',
            field=models.ManyToManyField(blank=True, to='Complain.Comment'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='vote',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Complain.Vote'),
        ),
    ]
