# Generated by Django 3.0.3 on 2020-10-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Verified_User', '0003_auto_20200929_1529'),
        ('Complain', '0015_auto_20201005_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Verified_User.Verified_User'),
        ),
    ]
