# Generated by Django 3.0.3 on 2020-10-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0008_delete_complaintag'),
        ('Complain', '0016_auto_20201005_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='tag',
            field=models.ManyToManyField(blank=True, to='Tag.Tag'),
        ),
    ]
