# Generated by Django 3.0.3 on 2020-10-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0017_auto_20201005_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='vote',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Complain.Vote'),
        ),
    ]
