# Generated by Django 3.0.3 on 2020-10-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0019_auto_20201005_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='downvote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='complain',
            name='upvote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='complain',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='complain',
            name='vote',
        ),
    ]
