# Generated by Django 3.0.3 on 2020-10-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0021_auto_20201005_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='comment',
            field=models.ManyToManyField(blank=True, to='Complain.Comment'),
        ),
        migrations.AddField(
            model_name='complain',
            name='downvote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='complain',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='complain',
            name='vote',
        ),
    ]
