# Generated by Django 3.0.3 on 2020-10-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0024_auto_20201005_1553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complain',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='complain',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='upvote',
        ),
    ]
