# Generated by Django 3.0.3 on 2020-10-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0026_auto_20201006_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
