# Generated by Django 2.2.5 on 2020-10-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0031_auto_20201007_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
