# Generated by Django 2.2.5 on 2020-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complain', '0032_auto_20201007_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complain',
            name='comment',
            field=models.ManyToManyField(blank=True, to='Complain.Comment'),
        ),
    ]
