# Generated by Django 3.0.3 on 2020-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verified_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
