# Generated by Django 3.0.3 on 2020-09-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20200923_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
